
from autotest.base_service_entity_handler import BaseServiceEntityHandler
from autotest.base_service_entity_handler_v2 import BaseServiceEntity as BaseServiceEntityV2
from autotest.meta_data_handler import BaseMetaDataHandler
from autotest.meta_data_handler_v2 import BaseMetaDataHandler as BaseMetaDataHandlerV2
from autotest.page_object import PageObject
from autotest.service_entity_factory import EntityFactory
import autotest.testdata_driver as testdata_driver

from autotest.lib.json_handler import getCleanJsonView
from autotest.lib.json_handler import getJsonData
from autotest.lib.json_handler import handle_item_in_json

from autotest.exception import BadStatusCodeException

import urllib3

urllib3.disable_warnings()